# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  runs-on: ubuntu-latest
  strategy:
      matrix:
        node-version: [10.x, 12.x]
  install:
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
  lint:
    needs: [install]
    steps:
      - run: npm lint
  test:
    needs: [install]
    steps:
    - uses: actions/checkout@v2
    
    - run: npm ci
    - run: npm test
env:
  CI: true